title: Joel Niles # your name (or website title) here
logo: "images/joe_profile.PNG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, my name is Joel and welcome to my GitHub portfolio page. This page is dedicated to sharing my python skills by showing off some of my past projects. I began coding in September 2021 using the Codecademy Data Science path and the projects displayed here are a combination of projects completed through that platform as well as indpendent projects completed using datasets from Kaggle. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/joel-niles1">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
